### ISSUE TITLE
Make the whole button a link

### ISSUE THREAD

**Issue by Barbapapazes** [selemondev/vscode-preview-docs#24]
Hello,

To open the docs, we need to click on the little button `read docs` but if the whole item was a button, it could help to open docs more easily.

![image](https://github.com/selemondev/vscode-preview-docs/assets/45267552/e9836e3c-3bfa-4bc3-b6b6-8e232eff1c46)

**Comment by selemondev** [comment]
Hey there @Barbapapazes , this enhancement will be featured in the next release 😀.
